/**
 * The one place the company's contact details are written down. Client-verified.
 *
 * Every card, button, footer row and piece of structured data on the site reads
 * from here — nothing hard-codes a number, and no translation file carries one.
 * The digits are identical in all seven locales by construction: only the label
 * around them is translated (see `common.phone` / `common.email` in messages/).
 */
export const contact = {
  /** Display form, spaced for reading. Print inside `dir="ltr"` so the leading
      `+` stays put on the Arabic pages. */
  phone: '+20 111 990 0389',
  /** E.164 — the machine-readable form, for `tel:` and structured data. */
  phoneE164: '+201119900389',
  phoneHref: 'tel:+201119900389',
  email: 'elmoloukfreshproduce@gmail.com',
  emailHref: 'mailto:elmoloukfreshproduce@gmail.com',
  whatsapp: 'https://wa.me/201119900389',
} as const;

/**
 * Central site config. Values marked [[confirm…]] are placeholders that must be
 * replaced with client-verified data before launch (see docs/03-launch-dependencies.md).
 * Nothing here is invented as fact.
 *
 * On the two names: `name` is the brand the visitor meets — it is what the
 * lockup in the header spells out, what the copy calls the company in all seven
 * languages, and therefore what belongs in a title, a share card and a home
 * screen. `legalName` is the registered entity behind it. Structured data
 * carries both so a crawler can reconcile the site with company records without
 * the browser chrome having to shout a name no page ever uses.
 */
export const siteConfig = {
  name: 'El Molouk',
  legalName: 'Kings For Import & Export',
  /**
   * Other names the same company trades under, for `Organization.alternateName`.
   * `logo.png` — the gold-lion import/export lockup — carries the third of
   * these, which is why it is listed rather than dismissed as a stray asset.
   */
  alternateNames: [
    'El Molouk Fresh Produce',
    'الملوك للاستيراد والتصدير',
    'Al-Muluk For Import & Export',
  ],
  domain: 'https://elmolouk.com',
  ...contact,
  legal: 'Kings For Import & Export', // [[confirm commercial registration no.]]
  address: '[[confirm packhouse address]]',
  /** ISO 3166-1 alpha-2. The only part of the address that is confirmed. */
  country: 'EG',
  /** `applicationName`, manifest `name`/`short_name`, and `og:site_name`. */
  shortName: 'El Molouk',
  /** Next's `metadata.category` — one string, so it stays the trade, not the crop. */
  category: 'Fresh Produce Export',
  industry: 'Fresh Produce Export',
  businessType: 'Egyptian Fresh Produce Exporter',
  /**
   * Browser chrome. Cream rather than white so the mobile address bar joins the
   * page instead of capping it with a band; mirrors `--color-cream`.
   */
  themeColor: '#fbf5ea',
  backgroundColor: '#fbf5ea',
  /**
   * Verified public profiles, emitted as `Organization.sameAs`. Empty until the
   * client supplies them — an unverified profile URL in structured data points
   * a crawler at an account that may not be theirs, so nothing is guessed.
   */
  social: [] as string[],
} as const;

/**
 * The three Open Graph cards, generated by `scripts/generate-brand-assets.mjs`.
 * Dimensions are written here rather than read from disk because `og:image:width`
 * and `og:image:height` must be in the HTML before a crawler fetches the image —
 * they are what stops a scraper guessing, or skipping the card entirely.
 */
export const OG_CARDS = {
  default: {url: '/og/og-default.jpg', width: 1200, height: 630, type: 'image/jpeg'},
  product: {url: '/og/og-product.jpg', width: 1200, height: 630, type: 'image/jpeg'},
  quality: {url: '/og/og-quality.jpg', width: 1200, height: 630, type: 'image/jpeg'},
} as const;

export type OgCard = keyof typeof OG_CARDS;

/** Primary navigation — limited to in-scope pages (no /about page in this build). */
export const NAV = [
  {key: 'sweetPotatoes', href: '/sweet-potatoes'},
  {key: 'quality', href: '/quality'},
  {key: 'contact', href: '/contact'},
] as const;
